CREATE TYPE "OrganizationSkuMode" AS ENUM ('SEQUENTIAL', 'PART_NUMBER');

ALTER TABLE "Organization"
ADD COLUMN "skuMode" "OrganizationSkuMode" NOT NULL DEFAULT 'SEQUENTIAL',
ADD COLUMN "skuPrefix" TEXT NOT NULL DEFAULT 'SKU',
ADD COLUMN "skuNextNumber" INTEGER NOT NULL DEFAULT 1000;
