"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "../../auth-ui.module.css";

const apiBase = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
interface Security { email: string; emailVerified: boolean; hasPassword: boolean; passwordChangedAt: string | null; mfaEnabled: boolean; recoveryCodesRemaining: number }

export default function AccountSecurity() {
  const [token, setToken] = useState(""); const [auth, setAuth] = useState<"loading"|"ready"|"required">("loading");
  const [security, setSecurity] = useState<Security | null>(null); const [setup, setSetup] = useState<{ secret: string; otpauthUri: string } | null>(null);
  const [codes, setCodes] = useState<string[]>([]); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { fetch(`${apiBase}/api/auth/refresh`, { method: "POST", credentials: "include" }).then(async (response) => response.ok ? response.json() : Promise.reject()).then((body: { accessToken: string }) => { setToken(body.accessToken); setAuth("ready"); }).catch(() => setAuth("required")); }, []);
  const request = useCallback(async (path: string, init: RequestInit = {}) => { const response = await fetch(`${apiBase}${path}`, { ...init, credentials: "include", headers: { ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers, Authorization: `Bearer ${token}` } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || body.issues?.[0]?.message || "Request failed"); return body; }, [token]);
  const load = useCallback(async () => { if (auth !== "ready") return; try { setSecurity(await request("/api/auth/security") as Security); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load account security"); } }, [auth, request]);
  useEffect(() => { void load(); }, [load]);
  function start(name: string) { setBusy(name); setError(""); setNotice(""); }
  async function password(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get("password") !== form.get("confirm")) { setError("Passwords do not match"); return; } start("password"); try { await request("/api/auth/password", { method: "POST", body: JSON.stringify({ currentPassword: String(form.get("currentPassword") || "") || undefined, password: form.get("password") }) }); window.location.assign("/login?security=password"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update password"); setBusy(""); } }
  async function beginMfa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); start("setup"); try { setSetup(await request("/api/auth/mfa/setup", { method: "POST", body: JSON.stringify({ password: new FormData(event.currentTarget).get("password") }) }) as { secret: string; otpauthUri: string }); setNotice("Add this key to your authenticator, then confirm a current six-digit code."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to begin MFA setup"); } finally { setBusy(""); } }
  async function confirmMfa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); start("confirm"); try { const result = await request("/api/auth/mfa/confirm", { method: "POST", body: JSON.stringify({ code: new FormData(event.currentTarget).get("code") }) }) as { recoveryCodes: string[] }; setCodes(result.recoveryCodes); setSetup(null); setNotice("MFA is enabled. Save every recovery code now; they will not be shown again."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to confirm MFA"); } finally { setBusy(""); } }
  async function sensitiveMfa(event: FormEvent<HTMLFormElement>, action: "disable"|"codes") { event.preventDefault(); start(action); const form = new FormData(event.currentTarget); try { if (action === "disable") { await request("/api/auth/mfa", { method: "DELETE", body: JSON.stringify({ password: form.get("password"), code: form.get("code") }) }); window.location.assign("/login?security=mfa-disabled"); } else { const result = await request("/api/auth/mfa/recovery-codes", { method: "POST", body: JSON.stringify({ password: form.get("password"), code: form.get("code") }) }) as { recoveryCodes: string[] }; setCodes(result.recoveryCodes); setNotice("Old recovery codes are invalid. Save this new set now."); await load(); } } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update MFA"); } finally { setBusy(""); } }
  async function logout() { setBusy("logout"); await fetch(`${apiBase}/api/auth/logout`, { method: "POST", credentials: "include" }).catch(() => undefined); window.location.assign("/login"); }
  async function copy(value: string) { await navigator.clipboard.writeText(value); setNotice("Copied securely."); }
  if (auth === "loading") return <main className={styles.spinner}>Loading account security…</main>;
  if (auth === "required") return <main className={styles.page}><section className={styles.card}><a className={styles.brand} href="/"><b>Part</b>Pulse</a><div className={styles.center}><h1>Sign in required</h1><p>Open a secure session before managing account security.</p><a href="/login">Sign in</a></div></section></main>;
  return <main className={styles.page}><section className={`${styles.card} ${styles.wide}`}><div className={styles.securityHeader}><div><a className={styles.brand} href="/catalog"><b>Part</b>Pulse</a><span className={styles.eyebrow}>ACCOUNT SECURITY</span><h1>Protect your access</h1><p>{security?.email}</p></div><button disabled={busy === "logout"} onClick={() => void logout()}>Sign out</button></div>
    {error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}
    {codes.length > 0 && <section className={styles.panel}><h2>One-time recovery codes</h2><p>Store these offline. Each code works once.</p><div className={styles.codes}>{codes.map((code) => <code key={code}>{code}</code>)}</div><button className={styles.primary} onClick={() => void copy(codes.join("\n"))}>Copy all codes</button></section>}
    <div className={styles.grid}><section className={styles.panel}><span className={styles.eyebrow}>PASSWORD</span><h2>{security?.hasPassword ? "Change password" : "Create password"}</h2><p>{security?.hasPassword ? "Changing it revokes every active refresh session." : "Invitation access created your account. Add a password for future sign-ins."}</p><form className={styles.form} onSubmit={password}>{security?.hasPassword && <label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label>}<label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} required/></label><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" required/></label><span className={styles.requirements}>12+ characters with uppercase, lowercase, number, and symbol.</span><button disabled={busy === "password"}>{busy === "password" ? "Updating…" : security?.hasPassword ? "Change password" : "Create password"}</button></form></section>
    <section className={styles.panel}><span className={styles.eyebrow}>MULTI-FACTOR AUTHENTICATION</span><h2>{security?.mfaEnabled ? "MFA enabled" : "Add an authenticator"}</h2><span className={`${styles.status} ${security?.mfaEnabled ? "" : styles.off}`}>{security?.mfaEnabled ? `${security.recoveryCodesRemaining} recovery codes remain` : "Optional"}</span>{!security?.hasPassword ? <p>Create a password before enabling MFA.</p> : !security?.mfaEnabled && !setup ? <form className={styles.form} onSubmit={beginMfa}><label>Confirm password<input name="password" type="password" required/></label><button disabled={busy === "setup"}>Begin MFA setup</button></form> : setup ? <><p>Enter this secret manually in Google Authenticator, Microsoft Authenticator, 1Password, or another TOTP app.</p><div className={styles.secret}>{setup.secret}</div><button onClick={() => void copy(setup.otpauthUri)}>Copy authenticator URI</button><form className={styles.form} onSubmit={confirmMfa}><label>Current six-digit code<input name="code" inputMode="numeric" autoComplete="one-time-code" required/></label><button disabled={busy === "confirm"}>Confirm and enable</button></form></> : <><form className={styles.form} onSubmit={(event) => void sensitiveMfa(event, "codes")}><label>Password<input name="password" type="password" required/></label><label>Authenticator or recovery code<input name="code" required/></label><button disabled={busy === "codes"}>Generate new recovery codes</button></form><form className={styles.form} onSubmit={(event) => void sensitiveMfa(event, "disable")}><label>Password<input name="password" type="password" required/></label><label>Authenticator or recovery code<input name="code" required/></label><button className={styles.danger} disabled={busy === "disable"}>Disable MFA and revoke sessions</button></form></>}</section></div>
    <div className={styles.links}><a href="/catalog">Return to catalog</a><a href="/admin/team">Team management</a></div>
  </section></main>;
}
