CREATE TYPE "FitmentJobStatus" AS ENUM ('QUEUED','RUNNING','REVIEW_REQUIRED','COMPLETED','PARTIAL','FAILED');
CREATE TYPE "FitmentJobItemStatus" AS ENUM ('QUEUED','RUNNING','REVIEW_REQUIRED','NO_CANDIDATE','APPROVED','FAILED');
CREATE TABLE "FitmentJob" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"createdById" TEXT NOT NULL,"marketplace" TEXT NOT NULL,"status" "FitmentJobStatus" NOT NULL DEFAULT 'QUEUED',"totalItems" INTEGER NOT NULL,"reviewedItems" INTEGER NOT NULL DEFAULT 0,"noCandidateItems" INTEGER NOT NULL DEFAULT 0,"failedItems" INTEGER NOT NULL DEFAULT 0,"startedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FitmentJob_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FitmentJobItem" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"fitmentJobId" TEXT NOT NULL,"partId" TEXT NOT NULL,"query" TEXT NOT NULL,"status" "FitmentJobItemStatus" NOT NULL DEFAULT 'QUEUED',"categoryId" TEXT,"categoryName" TEXT,"approvedCandidateId" TEXT,"metadataVersion" TEXT,"applicationCount" INTEGER NOT NULL DEFAULT 0,"error" TEXT,"startedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FitmentJobItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FitmentCandidate" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"fitmentJobItemId" TEXT NOT NULL,"epid" TEXT NOT NULL,"title" TEXT NOT NULL,"brand" TEXT,"imageUrl" TEXT,"productWebUrl" TEXT,"score" INTEGER NOT NULL,"matchedOn" TEXT[],"aspects" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "FitmentCandidate_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FitmentApplication" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"fitmentJobItemId" TEXT NOT NULL,"partId" TEXT NOT NULL,"fingerprint" TEXT NOT NULL,"properties" JSONB NOT NULL,"notes" TEXT,"approvedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "FitmentApplication_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FitmentJobItem_fitmentJobId_partId_key" ON "FitmentJobItem"("fitmentJobId","partId");
CREATE UNIQUE INDEX "FitmentJobItem_approvedCandidateId_key" ON "FitmentJobItem"("approvedCandidateId");
CREATE UNIQUE INDEX "FitmentCandidate_fitmentJobItemId_epid_key" ON "FitmentCandidate"("fitmentJobItemId","epid");
CREATE UNIQUE INDEX "FitmentApplication_fitmentJobItemId_fingerprint_key" ON "FitmentApplication"("fitmentJobItemId","fingerprint");
CREATE UNIQUE INDEX "FitmentJob_one_active_per_organization_key" ON "FitmentJob"("organizationId") WHERE "status" IN ('QUEUED','RUNNING');
CREATE INDEX "FitmentJob_organizationId_createdAt_idx" ON "FitmentJob"("organizationId","createdAt");
CREATE INDEX "FitmentJob_organizationId_status_idx" ON "FitmentJob"("organizationId","status");
CREATE INDEX "FitmentJobItem_organizationId_status_idx" ON "FitmentJobItem"("organizationId","status");
CREATE INDEX "FitmentJobItem_partId_completedAt_idx" ON "FitmentJobItem"("partId","completedAt");
CREATE INDEX "FitmentCandidate_organizationId_epid_idx" ON "FitmentCandidate"("organizationId","epid");
CREATE INDEX "FitmentCandidate_fitmentJobItemId_score_idx" ON "FitmentCandidate"("fitmentJobItemId","score");
CREATE INDEX "FitmentApplication_organizationId_partId_idx" ON "FitmentApplication"("organizationId","partId");
ALTER TABLE "FitmentJob" ADD CONSTRAINT "FitmentJob_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentJob" ADD CONSTRAINT "FitmentJob_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FitmentJobItem" ADD CONSTRAINT "FitmentJobItem_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentJobItem" ADD CONSTRAINT "FitmentJobItem_fitmentJobId_fkey" FOREIGN KEY ("fitmentJobId") REFERENCES "FitmentJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentJobItem" ADD CONSTRAINT "FitmentJobItem_partId_fkey" FOREIGN KEY ("partId") REFERENCES "Part"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentCandidate" ADD CONSTRAINT "FitmentCandidate_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentCandidate" ADD CONSTRAINT "FitmentCandidate_fitmentJobItemId_fkey" FOREIGN KEY ("fitmentJobItemId") REFERENCES "FitmentJobItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentJobItem" ADD CONSTRAINT "FitmentJobItem_approvedCandidateId_fkey" FOREIGN KEY ("approvedCandidateId") REFERENCES "FitmentCandidate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FitmentApplication" ADD CONSTRAINT "FitmentApplication_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentApplication" ADD CONSTRAINT "FitmentApplication_fitmentJobItemId_fkey" FOREIGN KEY ("fitmentJobItemId") REFERENCES "FitmentJobItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FitmentApplication" ADD CONSTRAINT "FitmentApplication_partId_fkey" FOREIGN KEY ("partId") REFERENCES "Part"("id") ON DELETE CASCADE ON UPDATE CASCADE;
