"use client";
import { FormEvent, useState } from "react";
import styles from "../auth-ui.module.css";
const apiBase = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
export default function ForgotPasswordForm() {
  const [done, setDone] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [devUrl, setDevUrl] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const email = new FormData(event.currentTarget).get("email"); try { const response = await fetch(`${apiBase}/api/auth/password-reset/request`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to request recovery"); setDevUrl(body.developmentUrl || ""); setDone(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to request recovery"); } finally { setBusy(false); } }
  return <main className={styles.page}><section className={styles.card}><a className={styles.brand} href="/"><b>Part</b>Pulse</a><span className={styles.eyebrow}>ACCOUNT RECOVERY</span><h1>{done ? "Check your email" : "Reset your password"}</h1>{done ? <><p>If an account exists for that email, a single-use recovery link has been sent.</p>{devUrl && <a className={styles.devLink} href={devUrl}>Development reset link</a>}<a href="/login">Return to sign in</a></> : <><p>We will send a one-hour password-reset link without disclosing whether the email is registered.</p>{error && <div className={styles.error}>{error}</div>}<form className={styles.form} onSubmit={submit}><label>Email<input name="email" type="email" autoComplete="email" required/></label><button disabled={busy}>{busy ? "Sending…" : "Send recovery link"}</button></form><a href="/login">Return to sign in</a></>}</section></main>;
}
